### PR TITLE
Keep up with ts-fsrs, update algorithm version to 5.0

### PR DESCRIPTION
**Pull request by ningkaiqiang**
- Delete original source file
- Implemented FSRS 5.0
- Add tests

### CODE REVIEW

**Comment by L-M-Sherlock** [comment]
@SplittyDev, @tomerbeil, @TrungNNg, @bensmiley, reviewer wanted.

**Comment by L-M-Sherlock** [comment]
We need add ci for this repo. I cannot review the code because I don't know swift.

**Comment by SplittyDev** [comment]
> I cannot review the code because I don't know swift.

Why did you merge it into main then? 😅

**Comment by L-M-Sherlock** [comment]
> Why did you merge it into main then? 😅

I confirm that all unit tests are passed. But the contributor hasn't added it to CI.

**Pull request merged**
